"""
plot_nav_metrics.py

Reads the CSV logs produced by main.py (stored in ./logs/) and generates
basic performance plots + a short console summary.

Files expected (generated by MissionRunner.save_logs()):
- logs/nav_metrics.csv       -> time series metrics (distance to path, goal, etc.)
- logs/targets_summary.csv   -> per-target summary (planning time, travel time, path length, ...)

What this script plots:
1) Lateral deviation (distance to planned path) over time: True vs PF
2) Bar chart: A* planning time per target
3) Bar chart: Travel time per target
4) Bar chart: Planned path length per target
5) Distance to current goal over time (PF)
"""

import csv
import os
from typing import List, Dict, Any

import matplotlib.pyplot as plt


# =============================================================================
# Configuration
# =============================================================================
LOG_DIR = "logs"
METRICS_FILE = os.path.join(LOG_DIR, "nav_metrics.csv")
TARGETS_FILE = os.path.join(LOG_DIR, "targets_summary.csv")


# =============================================================================
# Helpers
# =============================================================================
def read_csv_as_dicts(path: str) -> List[Dict[str, str]]:
    """Read a CSV file into a list of row dictionaries."""
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def f(row: Dict[str, str], key: str, default: float = 0.0) -> float:
    """Safe float parsing for CSV fields."""
    try:
        return float(row[key])
    except Exception:
        return default


def i(row: Dict[str, str], key: str, default: int = 0) -> int:
    """Safe int parsing (CSV may store as float strings)."""
    try:
        return int(float(row[key]))
    except Exception:
        return default


def ensure_exists(path: str, hint: str) -> None:
    """Fail early with a helpful message if a required file is missing."""
    if not os.path.exists(path):
        raise FileNotFoundError(f"Missing {path}. {hint}")


# =============================================================================
# Load data
# =============================================================================
ensure_exists(METRICS_FILE, "Run main.py first (it generates logs/nav_metrics.csv).")
ensure_exists(TARGETS_FILE, "Run main.py until at least one target is reached (it generates logs/targets_summary.csv).")

metric_rows = read_csv_as_dicts(METRICS_FILE)
target_rows = read_csv_as_dicts(TARGETS_FILE)

if not metric_rows:
    raise RuntimeError(f"{METRICS_FILE} exists but is empty.")
if not target_rows:
    raise RuntimeError(f"{TARGETS_FILE} exists but is empty.")

# --- Parse metrics time series ---
time_s = [f(r, "time_s") for r in metric_rows]
dist_to_path_true = [f(r, "dist_to_path_true_m") for r in metric_rows]
dist_to_path_pf = [f(r, "dist_to_path_pf_m") for r in metric_rows]
dist_to_goal_pf = [f(r, "dist_to_goal_pf_m") for r in metric_rows]

# --- Parse per-target summary ---
segments: List[Dict[str, Any]] = []
for r in target_rows:
    segments.append(
        {
            "segment": i(r, "segment"),
            "plan_time_s": f(r, "plan_time_s"),
            "path_length_m": f(r, "path_length_m"),
            "travel_time_s": f(r, "travel_time_s"),
            "t_start_s": f(r, "t_start_s"),
            "t_reached_s": f(r, "t_reached_s"),
            "mean_lat_err_true_m": f(r, "mean_lat_err_true_m"),
            "max_lat_err_true_m": f(r, "max_lat_err_true_m"),
            # NOTE: PF error fields are available in the CSV, but I keep the plots minimal here.
            "mean_lat_err_pf_m": f(r, "mean_lat_err_pf_m"),
            "max_lat_err_pf_m": f(r, "max_lat_err_pf_m"),
        }
    )

# Always sort by target id so plots are in order
segments.sort(key=lambda d: d["segment"])


# =============================================================================
# Console summary (quick readable report)
# =============================================================================
print("\n=== Navigation summary (per target) ===")
for s in segments:
    print(
        f"Target {s['segment']}: "
        f"plan={s['plan_time_s']*1000.0:.1f} ms | "
        f"path_len={s['path_length_m']:.2f} m | "
        f"travel={s['travel_time_s']:.2f} s | "
        f"mean_lat_true={s['mean_lat_err_true_m']:.3f} m | "
        f"max_lat_true={s['max_lat_err_true_m']:.3f} m"
    )
print("======================================\n")


# =============================================================================
# Plot 1 — Lateral deviation from planned path over time
# =============================================================================
plt.figure()
plt.plot(time_s, dist_to_path_true, label="Dist to planned path (True pose)")
plt.plot(time_s, dist_to_path_pf, label="Dist to planned path (PF pose)")

# Draw vertical lines when each segment is completed (reach time)
for s in segments:
    plt.axvline(s["t_reached_s"], linestyle="--", linewidth=1)

plt.xlabel("Time [s]")
plt.ylabel("Distance to planned path [m]")
plt.title("Lateral deviation from planned path")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()


# =============================================================================
# Plot 2 — Per-target bars (planning / travel / path length)
# =============================================================================
labels = [f"T{s['segment']}" for s in segments]
x = list(range(len(labels)))

plan_ms = [s["plan_time_s"] * 1000.0 for s in segments]
travel_s = [s["travel_time_s"] for s in segments]
path_len = [s["path_length_m"] for s in segments]

plt.figure()
plt.bar(x, plan_ms)
plt.xticks(x, labels)
plt.ylabel("A* planning time [ms]")
plt.title("A* planning time per target")
plt.grid(True, axis="y")
plt.tight_layout()
plt.show()

plt.figure()
plt.bar(x, travel_s)
plt.xticks(x, labels)
plt.ylabel("Travel time [s]")
plt.title("Robot travel time per target")
plt.grid(True, axis="y")
plt.tight_layout()
plt.show()

plt.figure()
plt.bar(x, path_len)
plt.xticks(x, labels)
plt.ylabel("Path length [m]")
plt.title("Planned path length per target")
plt.grid(True, axis="y")
plt.tight_layout()
plt.show()


# =============================================================================
# Plot 3 — Distance to current goal over time (PF)
# =============================================================================
plt.figure()
plt.plot(time_s, dist_to_goal_pf, label="Dist to goal (PF pose)")

for s in segments:
    plt.axvline(s["t_reached_s"], linestyle="--", linewidth=1)

plt.xlabel("Time [s]")
plt.ylabel("Distance [m]")
plt.title("Distance to current goal (PF)")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()